// <auto-generated />
using System;
using Backend.Model.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250327085906_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Model.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("AcceptedMarketingConsent")
                        .HasColumnType("bit");

                    b.Property<bool>("AcceptedRegulations")
                        .HasColumnType("bit");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("MemberSince")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nickname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("ReceiveEmailDailyUpdates")
                        .HasColumnType("bit");

                    b.Property<bool>("ReceiveEmailMatchClosed")
                        .HasColumnType("bit");

                    b.Property<bool>("ReceiveEmailNewGames")
                        .HasColumnType("bit");

                    b.Property<bool>("ReceiveEmailPendingBets")
                        .HasColumnType("bit");

                    b.Property<bool>("ReceiveEmailSpecialOffers")
                        .HasColumnType("bit");

                    b.Property<bool>("ReceiveEmailTournamentInvitation")
                        .HasColumnType("bit");

                    b.Property<bool>("ReceivePushDailyUpdates")
                        .HasColumnType("bit");

                    b.Property<bool>("ReceivePushMatchClosed")
                        .HasColumnType("bit");

                    b.Property<bool>("ReceivePushNewGames")
                        .HasColumnType("bit");

                    b.Property<bool>("ReceivePushPendingBets")
                        .HasColumnType("bit");

                    b.Property<bool>("ReceivePushSpecialOffers")
                        .HasColumnType("bit");

                    b.Property<bool>("ReceivePushTournamentInvitation")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Backend.Model.Entities.Bet", b =>
                {
                    b.Property<int>("BetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BetId"));

                    b.Property<int?>("AwayGoals")
                        .HasColumnType("int");

                    b.Property<decimal>("BaseAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BonusAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("HomeGoals")
                        .HasColumnType("int");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Payout")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Qualified")
                        .HasColumnType("int");

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("Submitted")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BetId");

                    b.HasIndex("MatchId");

                    b.HasIndex("UserId");

                    b.ToTable("Bets");
                });

            modelBuilder.Entity("Backend.Model.Entities.CustomMatch", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatchId"));

                    b.Property<decimal?>("AwayQualifies")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("int");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<decimal>("AwayWinOdds")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DrawOdds")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("HomeQualifies")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("int");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<decimal>("HomeWinOdds")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MatchStart")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PredefinedMatchId")
                        .HasColumnType("int");

                    b.Property<int?>("Qualified")
                        .HasColumnType("int");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("MatchId");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("PredefinedMatchId");

                    b.HasIndex("StageId");

                    b.HasIndex("TournamentId", "HomeTeamId", "AwayTeamId", "MatchStart")
                        .IsUnique();

                    b.ToTable("CustomMatches");
                });

            modelBuilder.Entity("Backend.Model.Entities.CustomMatchStage", b =>
                {
                    b.Property<int>("StageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StageId"));

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("PredefinedStageId")
                        .HasColumnType("int");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("StageId");

                    b.HasIndex("PredefinedStageId");

                    b.HasIndex("TournamentId");

                    b.ToTable("CustomMatchStages");
                });

            modelBuilder.Entity("Backend.Model.Entities.CustomTeam", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<int?>("PredefinedTeamId")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("TeamId");

                    b.HasIndex("PredefinedTeamId");

                    b.HasIndex("TournamentId");

                    b.ToTable("CustomTeams");
                });

            modelBuilder.Entity("Backend.Model.Entities.CustomTournament", b =>
                {
                    b.Property<int>("TournamentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TournamentId"));

                    b.Property<bool>("AllowBetsWithBooster")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowExactResultBonus")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowNonSubmittedBetsPenalty")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowWhoQualifiesBets")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ExactResultBonus")
                        .HasColumnType("int");

                    b.Property<int>("ExactResultBonusCalculation")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxBetBooster")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("NonSubmittedBetPenalty")
                        .HasColumnType("int");

                    b.Property<int?>("PredefinedTournamentId")
                        .HasColumnType("int");

                    b.Property<string>("PublicName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TotalBoosterPool")
                        .HasColumnType("int");

                    b.Property<int>("Update")
                        .HasColumnType("int");

                    b.Property<int>("Visibility")
                        .HasColumnType("int");

                    b.HasKey("TournamentId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PredefinedTournamentId");

                    b.ToTable("CustomTournaments");
                });

            modelBuilder.Entity("Backend.Model.Entities.CustomTournamentUserAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.Property<string>("UserAdminName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssignmentId");

                    b.HasIndex("TournamentId");

                    b.HasIndex("UserId", "TournamentId")
                        .IsUnique();

                    b.ToTable("CustomTournamentUserAssignments");
                });

            modelBuilder.Entity("Backend.Model.Entities.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("ISOCode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            ISOCode = "AF",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            LocationId = 2,
                            ISOCode = "AL",
                            Name = "Albania"
                        },
                        new
                        {
                            LocationId = 3,
                            ISOCode = "DZ",
                            Name = "Algeria"
                        },
                        new
                        {
                            LocationId = 4,
                            ISOCode = "AS",
                            Name = "American Samoa"
                        },
                        new
                        {
                            LocationId = 5,
                            ISOCode = "AD",
                            Name = "Andorra"
                        },
                        new
                        {
                            LocationId = 6,
                            ISOCode = "AO",
                            Name = "Angola"
                        },
                        new
                        {
                            LocationId = 7,
                            ISOCode = "AI",
                            Name = "Anguilla"
                        },
                        new
                        {
                            LocationId = 8,
                            ISOCode = "AQ",
                            Name = "Antarctica"
                        },
                        new
                        {
                            LocationId = 9,
                            ISOCode = "AG",
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            LocationId = 10,
                            ISOCode = "AR",
                            Name = "Argentina"
                        },
                        new
                        {
                            LocationId = 11,
                            ISOCode = "AM",
                            Name = "Armenia"
                        },
                        new
                        {
                            LocationId = 12,
                            ISOCode = "AW",
                            Name = "Aruba"
                        },
                        new
                        {
                            LocationId = 13,
                            ISOCode = "AU",
                            Name = "Australia"
                        },
                        new
                        {
                            LocationId = 14,
                            ISOCode = "AT",
                            Name = "Austria"
                        },
                        new
                        {
                            LocationId = 15,
                            ISOCode = "AZ",
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            LocationId = 16,
                            ISOCode = "BS",
                            Name = "Bahamas"
                        },
                        new
                        {
                            LocationId = 17,
                            ISOCode = "BH",
                            Name = "Bahrain"
                        },
                        new
                        {
                            LocationId = 18,
                            ISOCode = "BD",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            LocationId = 19,
                            ISOCode = "BB",
                            Name = "Barbados"
                        },
                        new
                        {
                            LocationId = 20,
                            ISOCode = "BY",
                            Name = "Belarus"
                        },
                        new
                        {
                            LocationId = 21,
                            ISOCode = "BE",
                            Name = "Belgium"
                        },
                        new
                        {
                            LocationId = 22,
                            ISOCode = "BZ",
                            Name = "Belize"
                        },
                        new
                        {
                            LocationId = 23,
                            ISOCode = "BJ",
                            Name = "Benin"
                        },
                        new
                        {
                            LocationId = 24,
                            ISOCode = "BM",
                            Name = "Bermuda"
                        },
                        new
                        {
                            LocationId = 25,
                            ISOCode = "BT",
                            Name = "Bhutan"
                        },
                        new
                        {
                            LocationId = 26,
                            ISOCode = "BO",
                            Name = "Bolivia, Plurinational State of"
                        },
                        new
                        {
                            LocationId = 27,
                            ISOCode = "BQ",
                            Name = "Bonaire, Sint Eustatius and Saba"
                        },
                        new
                        {
                            LocationId = 28,
                            ISOCode = "BA",
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            LocationId = 29,
                            ISOCode = "BW",
                            Name = "Botswana"
                        },
                        new
                        {
                            LocationId = 30,
                            ISOCode = "BV",
                            Name = "Bouvet Island"
                        },
                        new
                        {
                            LocationId = 31,
                            ISOCode = "BR",
                            Name = "Brazil"
                        },
                        new
                        {
                            LocationId = 32,
                            ISOCode = "IO",
                            Name = "British Indian Ocean Territory"
                        },
                        new
                        {
                            LocationId = 33,
                            ISOCode = "BN",
                            Name = "Brunei Darussalam"
                        },
                        new
                        {
                            LocationId = 34,
                            ISOCode = "BG",
                            Name = "Bulgaria"
                        },
                        new
                        {
                            LocationId = 35,
                            ISOCode = "BF",
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            LocationId = 36,
                            ISOCode = "BI",
                            Name = "Burundi"
                        },
                        new
                        {
                            LocationId = 37,
                            ISOCode = "CV",
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            LocationId = 38,
                            ISOCode = "KH",
                            Name = "Cambodia"
                        },
                        new
                        {
                            LocationId = 39,
                            ISOCode = "CM",
                            Name = "Cameroon"
                        },
                        new
                        {
                            LocationId = 40,
                            ISOCode = "CA",
                            Name = "Canada"
                        },
                        new
                        {
                            LocationId = 41,
                            ISOCode = "KY",
                            Name = "Cayman Islands"
                        },
                        new
                        {
                            LocationId = 42,
                            ISOCode = "CF",
                            Name = "Central African Republic"
                        },
                        new
                        {
                            LocationId = 43,
                            ISOCode = "TD",
                            Name = "Chad"
                        },
                        new
                        {
                            LocationId = 44,
                            ISOCode = "CL",
                            Name = "Chile"
                        },
                        new
                        {
                            LocationId = 45,
                            ISOCode = "CN",
                            Name = "China"
                        },
                        new
                        {
                            LocationId = 46,
                            ISOCode = "CX",
                            Name = "Christmas Island"
                        },
                        new
                        {
                            LocationId = 47,
                            ISOCode = "CC",
                            Name = "Cocos (Keeling) Islands"
                        },
                        new
                        {
                            LocationId = 48,
                            ISOCode = "CO",
                            Name = "Colombia"
                        },
                        new
                        {
                            LocationId = 49,
                            ISOCode = "KM",
                            Name = "Comoros"
                        },
                        new
                        {
                            LocationId = 50,
                            ISOCode = "CG",
                            Name = "Congo"
                        },
                        new
                        {
                            LocationId = 51,
                            ISOCode = "CD",
                            Name = "Congo, The Democratic Republic of the"
                        },
                        new
                        {
                            LocationId = 52,
                            ISOCode = "CK",
                            Name = "Cook Islands"
                        },
                        new
                        {
                            LocationId = 53,
                            ISOCode = "CR",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            LocationId = 54,
                            ISOCode = "HR",
                            Name = "Croatia"
                        },
                        new
                        {
                            LocationId = 55,
                            ISOCode = "CU",
                            Name = "Cuba"
                        },
                        new
                        {
                            LocationId = 56,
                            ISOCode = "CW",
                            Name = "Curaçao"
                        },
                        new
                        {
                            LocationId = 57,
                            ISOCode = "CY",
                            Name = "Cyprus"
                        },
                        new
                        {
                            LocationId = 58,
                            ISOCode = "CZ",
                            Name = "Czechia"
                        },
                        new
                        {
                            LocationId = 59,
                            ISOCode = "CI",
                            Name = "Côte d'Ivoire"
                        },
                        new
                        {
                            LocationId = 60,
                            ISOCode = "DK",
                            Name = "Denmark"
                        },
                        new
                        {
                            LocationId = 61,
                            ISOCode = "DJ",
                            Name = "Djibouti"
                        },
                        new
                        {
                            LocationId = 62,
                            ISOCode = "DM",
                            Name = "Dominica"
                        },
                        new
                        {
                            LocationId = 63,
                            ISOCode = "DO",
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            LocationId = 64,
                            ISOCode = "EC",
                            Name = "Ecuador"
                        },
                        new
                        {
                            LocationId = 65,
                            ISOCode = "EG",
                            Name = "Egypt"
                        },
                        new
                        {
                            LocationId = 66,
                            ISOCode = "SV",
                            Name = "El Salvador"
                        },
                        new
                        {
                            LocationId = 67,
                            ISOCode = "GQ",
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            LocationId = 68,
                            ISOCode = "ER",
                            Name = "Eritrea"
                        },
                        new
                        {
                            LocationId = 69,
                            ISOCode = "EE",
                            Name = "Estonia"
                        },
                        new
                        {
                            LocationId = 70,
                            ISOCode = "SZ",
                            Name = "Eswatini"
                        },
                        new
                        {
                            LocationId = 71,
                            ISOCode = "ET",
                            Name = "Ethiopia"
                        },
                        new
                        {
                            LocationId = 72,
                            ISOCode = "FK",
                            Name = "Falkland Islands (Malvinas)"
                        },
                        new
                        {
                            LocationId = 73,
                            ISOCode = "FO",
                            Name = "Faroe Islands"
                        },
                        new
                        {
                            LocationId = 74,
                            ISOCode = "FJ",
                            Name = "Fiji"
                        },
                        new
                        {
                            LocationId = 75,
                            ISOCode = "FI",
                            Name = "Finland"
                        },
                        new
                        {
                            LocationId = 76,
                            ISOCode = "FR",
                            Name = "France"
                        },
                        new
                        {
                            LocationId = 77,
                            ISOCode = "GF",
                            Name = "French Guiana"
                        },
                        new
                        {
                            LocationId = 78,
                            ISOCode = "PF",
                            Name = "French Polynesia"
                        },
                        new
                        {
                            LocationId = 79,
                            ISOCode = "TF",
                            Name = "French Southern Territories"
                        },
                        new
                        {
                            LocationId = 80,
                            ISOCode = "GA",
                            Name = "Gabon"
                        },
                        new
                        {
                            LocationId = 81,
                            ISOCode = "GM",
                            Name = "Gambia"
                        },
                        new
                        {
                            LocationId = 82,
                            ISOCode = "GE",
                            Name = "Georgia"
                        },
                        new
                        {
                            LocationId = 83,
                            ISOCode = "DE",
                            Name = "Germany"
                        },
                        new
                        {
                            LocationId = 84,
                            ISOCode = "GH",
                            Name = "Ghana"
                        },
                        new
                        {
                            LocationId = 85,
                            ISOCode = "GI",
                            Name = "Gibraltar"
                        },
                        new
                        {
                            LocationId = 86,
                            ISOCode = "GR",
                            Name = "Greece"
                        },
                        new
                        {
                            LocationId = 87,
                            ISOCode = "GL",
                            Name = "Greenland"
                        },
                        new
                        {
                            LocationId = 88,
                            ISOCode = "GD",
                            Name = "Grenada"
                        },
                        new
                        {
                            LocationId = 89,
                            ISOCode = "GP",
                            Name = "Guadeloupe"
                        },
                        new
                        {
                            LocationId = 90,
                            ISOCode = "GU",
                            Name = "Guam"
                        },
                        new
                        {
                            LocationId = 91,
                            ISOCode = "GT",
                            Name = "Guatemala"
                        },
                        new
                        {
                            LocationId = 92,
                            ISOCode = "GG",
                            Name = "Guernsey"
                        },
                        new
                        {
                            LocationId = 93,
                            ISOCode = "GN",
                            Name = "Guinea"
                        },
                        new
                        {
                            LocationId = 94,
                            ISOCode = "GW",
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            LocationId = 95,
                            ISOCode = "GY",
                            Name = "Guyana"
                        },
                        new
                        {
                            LocationId = 96,
                            ISOCode = "HT",
                            Name = "Haiti"
                        },
                        new
                        {
                            LocationId = 97,
                            ISOCode = "HM",
                            Name = "Heard Island and McDonald Islands"
                        },
                        new
                        {
                            LocationId = 98,
                            ISOCode = "VA",
                            Name = "Holy See (Vatican City State)"
                        },
                        new
                        {
                            LocationId = 99,
                            ISOCode = "HN",
                            Name = "Honduras"
                        },
                        new
                        {
                            LocationId = 100,
                            ISOCode = "HK",
                            Name = "Hong Kong"
                        },
                        new
                        {
                            LocationId = 101,
                            ISOCode = "HU",
                            Name = "Hungary"
                        },
                        new
                        {
                            LocationId = 102,
                            ISOCode = "IS",
                            Name = "Iceland"
                        },
                        new
                        {
                            LocationId = 103,
                            ISOCode = "IN",
                            Name = "India"
                        },
                        new
                        {
                            LocationId = 104,
                            ISOCode = "ID",
                            Name = "Indonesia"
                        },
                        new
                        {
                            LocationId = 105,
                            ISOCode = "IR",
                            Name = "Iran, Islamic Republic of"
                        },
                        new
                        {
                            LocationId = 106,
                            ISOCode = "IQ",
                            Name = "Iraq"
                        },
                        new
                        {
                            LocationId = 107,
                            ISOCode = "IE",
                            Name = "Ireland"
                        },
                        new
                        {
                            LocationId = 108,
                            ISOCode = "IM",
                            Name = "Isle of Man"
                        },
                        new
                        {
                            LocationId = 109,
                            ISOCode = "IL",
                            Name = "Israel"
                        },
                        new
                        {
                            LocationId = 110,
                            ISOCode = "IT",
                            Name = "Italy"
                        },
                        new
                        {
                            LocationId = 111,
                            ISOCode = "JM",
                            Name = "Jamaica"
                        },
                        new
                        {
                            LocationId = 112,
                            ISOCode = "JP",
                            Name = "Japan"
                        },
                        new
                        {
                            LocationId = 113,
                            ISOCode = "JE",
                            Name = "Jersey"
                        },
                        new
                        {
                            LocationId = 114,
                            ISOCode = "JO",
                            Name = "Jordan"
                        },
                        new
                        {
                            LocationId = 115,
                            ISOCode = "KZ",
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            LocationId = 116,
                            ISOCode = "KE",
                            Name = "Kenya"
                        },
                        new
                        {
                            LocationId = 117,
                            ISOCode = "KI",
                            Name = "Kiribati"
                        },
                        new
                        {
                            LocationId = 118,
                            ISOCode = "KP",
                            Name = "Korea, Democratic People's Republic of"
                        },
                        new
                        {
                            LocationId = 119,
                            ISOCode = "KR",
                            Name = "Korea, Republic of"
                        },
                        new
                        {
                            LocationId = 120,
                            ISOCode = "KW",
                            Name = "Kuwait"
                        },
                        new
                        {
                            LocationId = 121,
                            ISOCode = "KG",
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            LocationId = 122,
                            ISOCode = "LA",
                            Name = "Lao People's Democratic Republic"
                        },
                        new
                        {
                            LocationId = 123,
                            ISOCode = "LV",
                            Name = "Latvia"
                        },
                        new
                        {
                            LocationId = 124,
                            ISOCode = "LB",
                            Name = "Lebanon"
                        },
                        new
                        {
                            LocationId = 125,
                            ISOCode = "LS",
                            Name = "Lesotho"
                        },
                        new
                        {
                            LocationId = 126,
                            ISOCode = "LR",
                            Name = "Liberia"
                        },
                        new
                        {
                            LocationId = 127,
                            ISOCode = "LY",
                            Name = "Libya"
                        },
                        new
                        {
                            LocationId = 128,
                            ISOCode = "LI",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            LocationId = 129,
                            ISOCode = "LT",
                            Name = "Lithuania"
                        },
                        new
                        {
                            LocationId = 130,
                            ISOCode = "LU",
                            Name = "Luxembourg"
                        },
                        new
                        {
                            LocationId = 131,
                            ISOCode = "MO",
                            Name = "Macao"
                        },
                        new
                        {
                            LocationId = 132,
                            ISOCode = "MG",
                            Name = "Madagascar"
                        },
                        new
                        {
                            LocationId = 133,
                            ISOCode = "MW",
                            Name = "Malawi"
                        },
                        new
                        {
                            LocationId = 134,
                            ISOCode = "MY",
                            Name = "Malaysia"
                        },
                        new
                        {
                            LocationId = 135,
                            ISOCode = "MV",
                            Name = "Maldives"
                        },
                        new
                        {
                            LocationId = 136,
                            ISOCode = "ML",
                            Name = "Mali"
                        },
                        new
                        {
                            LocationId = 137,
                            ISOCode = "MT",
                            Name = "Malta"
                        },
                        new
                        {
                            LocationId = 138,
                            ISOCode = "MH",
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            LocationId = 139,
                            ISOCode = "MQ",
                            Name = "Martinique"
                        },
                        new
                        {
                            LocationId = 140,
                            ISOCode = "MR",
                            Name = "Mauritania"
                        },
                        new
                        {
                            LocationId = 141,
                            ISOCode = "MU",
                            Name = "Mauritius"
                        },
                        new
                        {
                            LocationId = 142,
                            ISOCode = "YT",
                            Name = "Mayotte"
                        },
                        new
                        {
                            LocationId = 143,
                            ISOCode = "MX",
                            Name = "Mexico"
                        },
                        new
                        {
                            LocationId = 144,
                            ISOCode = "FM",
                            Name = "Micronesia, Federated States of"
                        },
                        new
                        {
                            LocationId = 145,
                            ISOCode = "MD",
                            Name = "Moldova, Republic of"
                        },
                        new
                        {
                            LocationId = 146,
                            ISOCode = "MC",
                            Name = "Monaco"
                        },
                        new
                        {
                            LocationId = 147,
                            ISOCode = "MN",
                            Name = "Mongolia"
                        },
                        new
                        {
                            LocationId = 148,
                            ISOCode = "ME",
                            Name = "Montenegro"
                        },
                        new
                        {
                            LocationId = 149,
                            ISOCode = "MS",
                            Name = "Montserrat"
                        },
                        new
                        {
                            LocationId = 150,
                            ISOCode = "MA",
                            Name = "Morocco"
                        },
                        new
                        {
                            LocationId = 151,
                            ISOCode = "MZ",
                            Name = "Mozambique"
                        },
                        new
                        {
                            LocationId = 152,
                            ISOCode = "MM",
                            Name = "Myanmar"
                        },
                        new
                        {
                            LocationId = 153,
                            ISOCode = "NA",
                            Name = "Namibia"
                        },
                        new
                        {
                            LocationId = 154,
                            ISOCode = "NR",
                            Name = "Nauru"
                        },
                        new
                        {
                            LocationId = 155,
                            ISOCode = "NP",
                            Name = "Nepal"
                        },
                        new
                        {
                            LocationId = 156,
                            ISOCode = "NL",
                            Name = "Netherlands"
                        },
                        new
                        {
                            LocationId = 157,
                            ISOCode = "NC",
                            Name = "New Caledonia"
                        },
                        new
                        {
                            LocationId = 158,
                            ISOCode = "NZ",
                            Name = "New Zealand"
                        },
                        new
                        {
                            LocationId = 159,
                            ISOCode = "NI",
                            Name = "Nicaragua"
                        },
                        new
                        {
                            LocationId = 160,
                            ISOCode = "NE",
                            Name = "Niger"
                        },
                        new
                        {
                            LocationId = 161,
                            ISOCode = "NG",
                            Name = "Nigeria"
                        },
                        new
                        {
                            LocationId = 162,
                            ISOCode = "NU",
                            Name = "Niue"
                        },
                        new
                        {
                            LocationId = 163,
                            ISOCode = "NF",
                            Name = "Norfolk Island"
                        },
                        new
                        {
                            LocationId = 164,
                            ISOCode = "MK",
                            Name = "North Macedonia"
                        },
                        new
                        {
                            LocationId = 165,
                            ISOCode = "MP",
                            Name = "Northern Mariana Islands"
                        },
                        new
                        {
                            LocationId = 166,
                            ISOCode = "NO",
                            Name = "Norway"
                        },
                        new
                        {
                            LocationId = 167,
                            ISOCode = "OM",
                            Name = "Oman"
                        },
                        new
                        {
                            LocationId = 168,
                            ISOCode = "PK",
                            Name = "Pakistan"
                        },
                        new
                        {
                            LocationId = 169,
                            ISOCode = "PW",
                            Name = "Palau"
                        },
                        new
                        {
                            LocationId = 170,
                            ISOCode = "PS",
                            Name = "Palestine, State of"
                        },
                        new
                        {
                            LocationId = 171,
                            ISOCode = "PA",
                            Name = "Panama"
                        },
                        new
                        {
                            LocationId = 172,
                            ISOCode = "PG",
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            LocationId = 173,
                            ISOCode = "PY",
                            Name = "Paraguay"
                        },
                        new
                        {
                            LocationId = 174,
                            ISOCode = "PE",
                            Name = "Peru"
                        },
                        new
                        {
                            LocationId = 175,
                            ISOCode = "PH",
                            Name = "Philippines"
                        },
                        new
                        {
                            LocationId = 176,
                            ISOCode = "PN",
                            Name = "Pitcairn"
                        },
                        new
                        {
                            LocationId = 177,
                            ISOCode = "PL",
                            Name = "Poland"
                        },
                        new
                        {
                            LocationId = 178,
                            ISOCode = "PT",
                            Name = "Portugal"
                        },
                        new
                        {
                            LocationId = 179,
                            ISOCode = "PR",
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            LocationId = 180,
                            ISOCode = "QA",
                            Name = "Qatar"
                        },
                        new
                        {
                            LocationId = 181,
                            ISOCode = "RO",
                            Name = "Romania"
                        },
                        new
                        {
                            LocationId = 182,
                            ISOCode = "RU",
                            Name = "Russian Federation"
                        },
                        new
                        {
                            LocationId = 183,
                            ISOCode = "RW",
                            Name = "Rwanda"
                        },
                        new
                        {
                            LocationId = 184,
                            ISOCode = "RE",
                            Name = "Réunion"
                        },
                        new
                        {
                            LocationId = 185,
                            ISOCode = "BL",
                            Name = "Saint Barthélemy"
                        },
                        new
                        {
                            LocationId = 186,
                            ISOCode = "SH",
                            Name = "Saint Helena, Ascension and Tristan da Cunha"
                        },
                        new
                        {
                            LocationId = 187,
                            ISOCode = "KN",
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            LocationId = 188,
                            ISOCode = "LC",
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            LocationId = 189,
                            ISOCode = "MF",
                            Name = "Saint Martin (French part)"
                        },
                        new
                        {
                            LocationId = 190,
                            ISOCode = "PM",
                            Name = "Saint Pierre and Miquelon"
                        },
                        new
                        {
                            LocationId = 191,
                            ISOCode = "VC",
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            LocationId = 192,
                            ISOCode = "WS",
                            Name = "Samoa"
                        },
                        new
                        {
                            LocationId = 193,
                            ISOCode = "SM",
                            Name = "San Marino"
                        },
                        new
                        {
                            LocationId = 194,
                            ISOCode = "ST",
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            LocationId = 195,
                            ISOCode = "SA",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            LocationId = 196,
                            ISOCode = "SN",
                            Name = "Senegal"
                        },
                        new
                        {
                            LocationId = 197,
                            ISOCode = "RS",
                            Name = "Serbia"
                        },
                        new
                        {
                            LocationId = 198,
                            ISOCode = "SC",
                            Name = "Seychelles"
                        },
                        new
                        {
                            LocationId = 199,
                            ISOCode = "SL",
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            LocationId = 200,
                            ISOCode = "SG",
                            Name = "Singapore"
                        },
                        new
                        {
                            LocationId = 201,
                            ISOCode = "SX",
                            Name = "Sint Maarten (Dutch part)"
                        },
                        new
                        {
                            LocationId = 202,
                            ISOCode = "SK",
                            Name = "Slovakia"
                        },
                        new
                        {
                            LocationId = 203,
                            ISOCode = "SI",
                            Name = "Slovenia"
                        },
                        new
                        {
                            LocationId = 204,
                            ISOCode = "SB",
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            LocationId = 205,
                            ISOCode = "SO",
                            Name = "Somalia"
                        },
                        new
                        {
                            LocationId = 206,
                            ISOCode = "ZA",
                            Name = "South Africa"
                        },
                        new
                        {
                            LocationId = 207,
                            ISOCode = "GS",
                            Name = "South Georgia and the South Sandwich Islands"
                        },
                        new
                        {
                            LocationId = 208,
                            ISOCode = "SS",
                            Name = "South Sudan"
                        },
                        new
                        {
                            LocationId = 209,
                            ISOCode = "ES",
                            Name = "Spain"
                        },
                        new
                        {
                            LocationId = 210,
                            ISOCode = "LK",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            LocationId = 211,
                            ISOCode = "SD",
                            Name = "Sudan"
                        },
                        new
                        {
                            LocationId = 212,
                            ISOCode = "SR",
                            Name = "Suriname"
                        },
                        new
                        {
                            LocationId = 213,
                            ISOCode = "SJ",
                            Name = "Svalbard and Jan Mayen"
                        },
                        new
                        {
                            LocationId = 214,
                            ISOCode = "SE",
                            Name = "Sweden"
                        },
                        new
                        {
                            LocationId = 215,
                            ISOCode = "CH",
                            Name = "Switzerland"
                        },
                        new
                        {
                            LocationId = 216,
                            ISOCode = "SY",
                            Name = "Syrian Arab Republic"
                        },
                        new
                        {
                            LocationId = 217,
                            ISOCode = "TW",
                            Name = "Taiwan, Province of China"
                        },
                        new
                        {
                            LocationId = 218,
                            ISOCode = "TJ",
                            Name = "Tajikistan"
                        },
                        new
                        {
                            LocationId = 219,
                            ISOCode = "TZ",
                            Name = "Tanzania, United Republic of"
                        },
                        new
                        {
                            LocationId = 220,
                            ISOCode = "TH",
                            Name = "Thailand"
                        },
                        new
                        {
                            LocationId = 221,
                            ISOCode = "TL",
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            LocationId = 222,
                            ISOCode = "TG",
                            Name = "Togo"
                        },
                        new
                        {
                            LocationId = 223,
                            ISOCode = "TK",
                            Name = "Tokelau"
                        },
                        new
                        {
                            LocationId = 224,
                            ISOCode = "TO",
                            Name = "Tonga"
                        },
                        new
                        {
                            LocationId = 225,
                            ISOCode = "TT",
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            LocationId = 226,
                            ISOCode = "TN",
                            Name = "Tunisia"
                        },
                        new
                        {
                            LocationId = 227,
                            ISOCode = "TR",
                            Name = "Turkey"
                        },
                        new
                        {
                            LocationId = 228,
                            ISOCode = "TM",
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            LocationId = 229,
                            ISOCode = "TC",
                            Name = "Turks and Caicos Islands"
                        },
                        new
                        {
                            LocationId = 230,
                            ISOCode = "TV",
                            Name = "Tuvalu"
                        },
                        new
                        {
                            LocationId = 231,
                            ISOCode = "UG",
                            Name = "Uganda"
                        },
                        new
                        {
                            LocationId = 232,
                            ISOCode = "UA",
                            Name = "Ukraine"
                        },
                        new
                        {
                            LocationId = 233,
                            ISOCode = "AE",
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            LocationId = 234,
                            ISOCode = "GB",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            LocationId = 235,
                            ISOCode = "US",
                            Name = "United States"
                        },
                        new
                        {
                            LocationId = 236,
                            ISOCode = "UM",
                            Name = "United States Minor Outlying Islands"
                        },
                        new
                        {
                            LocationId = 237,
                            ISOCode = "UY",
                            Name = "Uruguay"
                        },
                        new
                        {
                            LocationId = 238,
                            ISOCode = "UZ",
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            LocationId = 239,
                            ISOCode = "VU",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            LocationId = 240,
                            ISOCode = "VE",
                            Name = "Venezuela, Bolivarian Republic of"
                        },
                        new
                        {
                            LocationId = 241,
                            ISOCode = "VN",
                            Name = "Viet Nam"
                        },
                        new
                        {
                            LocationId = 242,
                            ISOCode = "VG",
                            Name = "Virgin Islands, British"
                        },
                        new
                        {
                            LocationId = 243,
                            ISOCode = "VI",
                            Name = "Virgin Islands, U.S."
                        },
                        new
                        {
                            LocationId = 244,
                            ISOCode = "WF",
                            Name = "Wallis and Futuna"
                        },
                        new
                        {
                            LocationId = 245,
                            ISOCode = "EH",
                            Name = "Western Sahara"
                        },
                        new
                        {
                            LocationId = 246,
                            ISOCode = "YE",
                            Name = "Yemen"
                        },
                        new
                        {
                            LocationId = 247,
                            ISOCode = "ZM",
                            Name = "Zambia"
                        },
                        new
                        {
                            LocationId = 248,
                            ISOCode = "ZW",
                            Name = "Zimbabwe"
                        },
                        new
                        {
                            LocationId = 249,
                            ISOCode = "AX",
                            Name = "Åland Islands"
                        });
                });

            modelBuilder.Entity("Backend.Model.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Backend.Model.Entities.NotificationRecipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("NotificationId")
                        .HasColumnType("int");

                    b.Property<bool>("SentEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("SentPush")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("NotificationRecipients");
                });

            modelBuilder.Entity("Backend.Model.Entities.PredefinedMatch", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatchId"));

                    b.Property<decimal?>("AwayQualifies")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("int");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<decimal>("AwayWinOdds")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DrawOdds")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("HomeQualifies")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("int");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<decimal>("HomeWinOdds")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MatchStart")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Qualified")
                        .HasColumnType("int");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("MatchId");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("StageId");

                    b.HasIndex("TournamentId");

                    b.ToTable("PredefinedMatches");
                });

            modelBuilder.Entity("Backend.Model.Entities.PredefinedMatchStage", b =>
                {
                    b.Property<int>("StageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StageId"));

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("StageId");

                    b.HasIndex("TournamentId");

                    b.ToTable("PredefinedMatchStages");
                });

            modelBuilder.Entity("Backend.Model.Entities.PredefinedTeam", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<int>("PredefinedTournamentId")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TeamId");

                    b.HasIndex("PredefinedTournamentId");

                    b.ToTable("PredefinedTeams");
                });

            modelBuilder.Entity("Backend.Model.Entities.PredefinedTournament", b =>
                {
                    b.Property<int>("TournamentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TournamentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TournamentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Update")
                        .HasColumnType("int");

                    b.HasKey("TournamentId");

                    b.ToTable("PredefinedTournaments");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "3",
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Backend.Model.Entities.ApplicationUser", b =>
                {
                    b.HasOne("Backend.Model.Entities.Location", "Location")
                        .WithMany("Users")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Backend.Model.Entities.Bet", b =>
                {
                    b.HasOne("Backend.Model.Entities.CustomMatch", "Match")
                        .WithMany("Bets")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Model.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Model.Entities.CustomMatch", b =>
                {
                    b.HasOne("Backend.Model.Entities.CustomTeam", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Model.Entities.CustomTeam", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Model.Entities.PredefinedMatch", "PredefinedSource")
                        .WithMany()
                        .HasForeignKey("PredefinedMatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend.Model.Entities.CustomMatchStage", "Stage")
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Model.Entities.CustomTournament", "Tournament")
                        .WithMany("Matches")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("PredefinedSource");

                    b.Navigation("Stage");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Backend.Model.Entities.CustomMatchStage", b =>
                {
                    b.HasOne("Backend.Model.Entities.PredefinedMatchStage", "PredefinedSource")
                        .WithMany()
                        .HasForeignKey("PredefinedStageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend.Model.Entities.CustomTournament", "Tournament")
                        .WithMany("Stages")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PredefinedSource");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Backend.Model.Entities.CustomTeam", b =>
                {
                    b.HasOne("Backend.Model.Entities.PredefinedTeam", "PredefinedSource")
                        .WithMany()
                        .HasForeignKey("PredefinedTeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend.Model.Entities.CustomTournament", "Tournament")
                        .WithMany("Teams")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PredefinedSource");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Backend.Model.Entities.CustomTournament", b =>
                {
                    b.HasOne("Backend.Model.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Model.Entities.PredefinedTournament", "PredefinedSource")
                        .WithMany()
                        .HasForeignKey("PredefinedTournamentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("PredefinedSource");
                });

            modelBuilder.Entity("Backend.Model.Entities.CustomTournamentUserAssignment", b =>
                {
                    b.HasOne("Backend.Model.Entities.CustomTournament", "Tournament")
                        .WithMany("Participants")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Model.Entities.ApplicationUser", "User")
                        .WithMany("CustomTournamentUserAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tournament");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Model.Entities.NotificationRecipient", b =>
                {
                    b.HasOne("Backend.Model.Entities.Notification", "Notification")
                        .WithMany()
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Model.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Model.Entities.PredefinedMatch", b =>
                {
                    b.HasOne("Backend.Model.Entities.PredefinedTeam", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Model.Entities.PredefinedTeam", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Model.Entities.PredefinedMatchStage", "PredefinedStage")
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Model.Entities.PredefinedTournament", "PredefinedTournament")
                        .WithMany("PredefinedMatches")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("PredefinedStage");

                    b.Navigation("PredefinedTournament");
                });

            modelBuilder.Entity("Backend.Model.Entities.PredefinedMatchStage", b =>
                {
                    b.HasOne("Backend.Model.Entities.PredefinedTournament", "PredefinedTournament")
                        .WithMany("PredefinedStages")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PredefinedTournament");
                });

            modelBuilder.Entity("Backend.Model.Entities.PredefinedTeam", b =>
                {
                    b.HasOne("Backend.Model.Entities.PredefinedTournament", "PredefinedTournament")
                        .WithMany("PredefinedTeams")
                        .HasForeignKey("PredefinedTournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PredefinedTournament");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Backend.Model.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Backend.Model.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Model.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Backend.Model.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Model.Entities.ApplicationUser", b =>
                {
                    b.Navigation("CustomTournamentUserAssignments");
                });

            modelBuilder.Entity("Backend.Model.Entities.CustomMatch", b =>
                {
                    b.Navigation("Bets");
                });

            modelBuilder.Entity("Backend.Model.Entities.CustomTournament", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Participants");

                    b.Navigation("Stages");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Backend.Model.Entities.Location", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Backend.Model.Entities.PredefinedTournament", b =>
                {
                    b.Navigation("PredefinedMatches");

                    b.Navigation("PredefinedStages");

                    b.Navigation("PredefinedTeams");
                });
#pragma warning restore 612, 618
        }
    }
}
